apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 3
  template:
    metadata:
      annotations:
         pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: 10.100.97.89:5000/cassandra
        #image: gcr.io/google-samples/cassandra:v9
        imagePullPolicy: Always
        command:
          - /run.sh
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        # If you need it it is going away in C* 4.0
        #- containerPort: 9160
        #  name: thrift
        resources:
          request:
            cpu: 1
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

        # CJL figure this out
        #args:
        #- --on-start="/on-start.sh"
        #- --service=cassandra

        volumeMounts:
        # These volume mounts are persistent. They're like inline claims,
        # but not exactly because the names need to match exactly one of
        # the pet volumes.
        - name: cass_datadir
          mountPath: /cassandra_data

  volumeClaimTemplates:
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  - metadata:
      name: cass_datadir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
